import type { Product } from "@/lib/types"

export const products: Product[] = [
  {
    id: "coffee-mug",
    name: "Coffee Mug",
    price: 12.99,
    category: "Kitchenware",
    image: "/placeholder.svg?height=300&width=300",
    description: "A premium ceramic coffee mug perfect for your morning brew. Holds 12oz of your favorite beverage.",
  },
  {
    id: "wireless-mouse",
    name: "Wireless Mouse",
    price: 24.99,
    category: "Electronics",
    image: "/placeholder.svg?height=300&width=300",
    description: "Ergonomic wireless mouse with precision tracking and long battery life.",
  },
  {
    id: "notebook",
    name: "Notebook",
    price: 4.99,
    category: "Stationery",
    image: "/placeholder.svg?height=300&width=300",
    description: "High-quality lined notebook with 120 pages and durable cover.",
  },
  {
    id: "water-bottle",
    name: "Water Bottle",
    price: 15.99,
    category: "Kitchenware",
    image: "/placeholder.svg?height=300&width=300",
    description: "Insulated stainless steel water bottle that keeps drinks cold for 24 hours or hot for 12 hours.",
  },
  {
    id: "headphones",
    name: "Headphones",
    price: 59.99,
    category: "Electronics",
    image: "/placeholder.svg?height=300&width=300",
    description: "Over-ear headphones with noise cancellation and premium sound quality.",
  },
  {
    id: "desk-lamp",
    name: "Desk Lamp",
    price: 29.99,
    category: "Home",
    image: "/placeholder.svg?height=300&width=300",
    description: "Adjustable LED desk lamp with multiple brightness levels and color temperatures.",
  },
  {
    id: "usb-drive",
    name: "USB Drive",
    price: 14.99,
    category: "Electronics",
    image: "/placeholder.svg?height=300&width=300",
    description: "64GB USB 3.0 flash drive for fast data transfer and storage.",
  },
  {
    id: "backpack",
    name: "Backpack",
    price: 39.99,
    category: "Accessories",
    image: "/placeholder.svg?height=300&width=300",
    description: "Durable backpack with multiple compartments, perfect for work or school.",
  },
  {
    id: "bluetooth-speaker",
    name: "Bluetooth Speaker",
    price: 49.99,
    category: "Audio",
    image: "/placeholder.svg?height=300&width=300",
    description: "Portable Bluetooth speaker with 20-hour battery life and waterproof design.",
  },
  {
    id: "smart-watch",
    name: "Smart Watch",
    price: 129.99,
    category: "Electronics",
    image: "/placeholder.svg?height=300&width=300",
    description: "Feature-rich smartwatch with fitness tracking, notifications, and customizable watch faces.",
  },
  {
    id: "wireless-charger",
    name: "Wireless Charger",
    price: 19.99,
    category: "Electronics",
    image: "/placeholder.svg?height=300&width=300",
    description: "Fast wireless charging pad compatible with all Qi-enabled devices.",
  },
  {
    id: "plant-pot",
    name: "Plant Pot",
    price: 8.99,
    category: "Home",
    image: "/placeholder.svg?height=300&width=300",
    description: "Ceramic plant pot with drainage hole, perfect for indoor plants and herbs.",
  },
]

